config:

  siteName: Unipol-Prod

  debug: true

  server:
    api:
      port: 8088
    ssl:
      enable: false
      port: 8443
      key: ./ssl/private.pem
      cert: ./ssl/dcsi.crt
    ftp:
      enable: false
      port: 8021
      username: terry
      password: 12345678
      initialCwd: /Users/ytc0316/Downloads/ftp-root
      rootPath: /
      debugLevel: 0

  elastic:
    conf:
      log: warning
      hosts: [http://172.31.4.0:9200]
      requestTimeout: 300000
      keepAlive: true
      maxSockets: 256
      keepAliveMaxFreeSockets: 30

  ftp:
    basePath: files/unipol-prod/
    conf:
      host: 10.243.170.74
      user: postmaster
      password: sercomm1234

  kibana:
    conf:
      host: http://13.115.15.163:5601

  mysql:
    conf:
      connectionLimit: 10
      host: 10.243.170.79
      user: cms
      password: ability123
      database: n_cms_core

  redis:
    conf:
      host: 10.243.170.97
      port: 6379
      password: 

  mail:
    host: mail.smartgaiacloud.com
    port: 25
    auth:
      user: postmaster
      pass: ability123
    tls:
      # do not fail on invalid certs
      rejectUnauthorized: false

  mqtt:
    enable: True
    conf:
      protocol: tcp
      host: shpdllb.northeurope.cloudapp.azure.com
      port: 1883
      options:
        durable: true
      username: mqttclient
      password: ability123

  service:
    cmsi: [{protocol: http, host: shpcms.sunto.reply.it, port: 8080}]
    dcsi: [{protocol: http, host: 127.0.0.1, port: 8088}]
    dns: [{protocol: udp, host: 10.243.170.68, port: 53}]
    bmsi: [{protocol: http, host: shpcms.sunto.reply.it, port: 8080}]
    fwUpgrade: [{protocol: http, host: shpcms.sunto.reply.it, port: 8080}]

  logger:
    # error: 0 warn: 1 info: 2 verbose: 3 debug: 4 silly: 5 
    - transport: console
      options:
        level: info
        colorize: true
        json: true
        timestampFormat: YYYY-MM-DDTHH:mm:ss.SSSZZ
    - transport: rotate_file
      options:
        level: debug
        filename: ./log/log
        datePattern: yyyy-MM-dd.
        prepend: true
        json: true
        timestampFormat: YYYY-MM-DDTHH:mm:ss.SSSZZ

# Automation module
scheduleNotification:

  # Dump ip device cache from redis into elasticsearch
  ipDevice:
    enable: True
    cronTime: 0 15,45 * * * *
    # Creates an array of elements split into groups the length of size
    chunkSize: 1200
    # Array of firmware version excluded in history cache
    excludedFwVersion4Histort: ['', '1', '1.0']
    # Pick properties in history cache for bulk
    keptProperties4Histort: [mac, devStatus, devStatusDisplay, '@timestamp', name, model, type, fwVersion, kitcode, enable, internetAccess, security.arm]

  # Dump rf device cache from redis into elasticsearch
  rfDevice:
    enable: True 
    cronTime: 0 55 1-23/2 * * *
    # Creates an array of elements split into groups the length of size
    chunkSize: 1000

  # In elasticsearch search gateways and cameras for the last offline & online and then save to index of kit_status-* 
  kitStatus:
    enable: True
    cronTime: 0 5 7 * * *
    # Creates an array of elements split into groups the length of size
    chunkSize: 1200
    intervalBeforeSearchEvent: 7776000
    # Wait for Logstash to fill the data, and then shift time point for searching
    shift: forward
    shiftInterval: 300

  # Notify the devices that generated the specified event via email or FTP, and so ask devices do something
  eventNotification:
    enable: True
    cronTime: 0 5 */2 * * *
    interval: 7200
    intervalAfterSpecialEvent: 600
    intervalBeforeOfflineEvent: 7776000
    intervalBeforeOfflineKpi: 604800
    intervalBeforeSpecialEvent: 86400
    # Wait for Logstash to fill the data, and then shift time point for searching
    shift: forward
    shiftInterval: 300
    # Nodemailer options
    sendMail:
      options:
        from: postmaster@smartgaiacloud.com
        to: lee_shen@sercomm.com, louis_shih@Sercomm.com, terry_chen@sercomm.com, eric_kao@sercomm.com, schroeder_chung@sercomm.com, jordan_chen@sercomm.com, henry_shiu@sercomm.com, terry_liu@sercomm.com
        subject: gateway online offline notification
        errorRecipient: ytc0316@msn.com
        errorMessage: notification fail
    # Ftp server info for result to send
    putFtp:
      options:
        host: 10.243.170.74
        user: postmaster
        password: sercomm1234
      path: files/unipol-prod/
    contents:
      - key: gatewayOnline
        enable: true
        eventCode: 99011
        # Mail content for sending
        mail:
          fileName: gateway_online.csv
          tableTitle: Gateway Online
          tableHeader: [index, kitcode, gw_mac, camera_mac, ac_to_dc, dc_to_ac, low_battery, reboot_time, sub_code, offline_time, online_time, fw_version]
        # File info for ftp
        ftp:
          fileName: gateway_online
          fileExtension: csv
        # Job content template
        job:
          name: gateway online notification
          kitcodes: []
          parameters: [{name: FILE_PATH, value: files/unipol-prod/scheduleLog/}]
          templateIds: [get_bundle_log, get_all_gw_log]
      - key: gatewayBootup
        enable: true
        eventCode: 30007
        # Mail content for sending
        mail:
          fileName: gateway_bootup.csv
          tableTitle: Gateway Bootup
          tableHeader: [index, kitcode, gw_mac, gw_time, srv_time, sub_code, fw_version]
        # File info for ftp
        ftp:
          fileName: gateway_bootup
          fileExtension: csv
        # Job content template
        job:
          name: gateway bootup notification
          kitcodes: []
          parameters: [{name: FILE_PATH, value: files/unipol-prod/scheduleLog/}]
          templateIds: [get_system_log]
      - key: cameraOffline
        enable: true
        eventCode: 99003
        # Mail content for sending
        mail:
          fileName: camera_offline.csv
          tableTitle: Camera Offline
          tableHeader: [index, kitcode, gw_mac, camera_mac, gw_online, gw_offline, camera_online, camera_offline, fw_version]
          shiftCameraOffline: backward
          shiftCameraOfflineInterval: 600
        # File info for ftp
        ftp:
          fileName: camera_offline
          fileExtension: csv
        # Job content template
        job:
          name: camera offline notification
          kitcodes: []
          parameters: [{name: FILE_PATH, value: files/unipol-prod/scheduleLog/}]
          templateIds: [get_bundle_log, get_arp, ping_ip_camera, get_all_gw_log, execute_ping_cms, execute_traceroute_cms, execute_ping_mqtt, execute_traceroute_mqtt, execute_ifconfig, execute_ps, execute_route]
      - key: cameraOnline
        enable: true
        eventCode: 99010
        # Mail content for sending
        mail:
          fileName: camera_online.csv
          tableTitle: Camera Online
          tableHeader: [index, kitcode, gw_mac, camera_mac, gw_offline, gw_online, camera_offline, camera_online, fw_version]
          shiftCameraOnline: backward
          shiftCameraOnlineInterval: 600
        # File info for ftp
        ftp:
          fileName: camera_online
          fileExtension: csv
        # Job content template
        job:
          name: camera online notification
          kitcodes: []
          parameters: [{name: FILE_PATH, value: files/unipol-prod/scheduleLog/}]
          templateIds: [get_ip_camera_log]
      - key: sensorOffline
        enable: true
        eventCode: 11006
        # Mail content for sending
        mail:
          fileName: sensor_offline.csv
          tableTitle: Sensor Offline
          tableHeader: [index, kitcode, gw_mac, rf_zid, u_type, gw_time, srv_time, fw_version, last_3rd_rssi_inst, last_3rd_lqi_inst, last_2nd_rssi_inst, last_2nd_lqi_inst, last_rssi_inst, last_lqi_inst, last_rssi_ave, last_lqi_ave]
        # File info for ftp
        ftp:
          fileName: sensor_offline
          fileExtension: csv
        # Job content template
        job:
          name: sensor offline notification
          kitcodes: []
          parameters: [{name: FILE_PATH, value: files/unipol-prod/scheduleLog/}]
          templateIds: [get_wifi_channel, get_site_survey]

  # Search data related to the gateway that occurs events during the specified time
  kitReport:
    enable: True
    cronTime: 0 5 5 * * *
    # Creates an array of elements split into groups the length of size
    chunkSize: 300
    highBatteryTemperature: 400
    interval: 86400
    intervalBeforeSearchEvent: 7776000
    # Wait for Logstash to fill the data, and then shift time point for searching
    shift: forward
    shiftInterval: 300
    # Nodemailer options
    sendMail:
      options:
        from: postmaster@smartgaiacloud.com
        to: lee_shen@sercomm.com, louis_shih@Sercomm.com, terry_chen@sercomm.com, jordan_chen@sercomm.com, henry_shiu@sercomm.com, terry_liu@sercomm.com
        subject: Daily Data for Offline analysis
        errorRecipient: ytc0316@msn.com
        errorMessage: kit report fail
    # Ftp server info for result to send
    putFtp:
      options:
        host: 10.243.170.74
        user: postmaster
        password: sercomm1234
      path: files/unipol-prod/
    contents:
      - key: kitReport
        # Mail content for sending
        mail:
          fileName: daily_data.csv
          tableTitle: Daily Data for Offline analysis
          tableHeader: [index, kitcode, fw_version, last_3rd_offline_time, last_3rd_online_time, last_2nd_offline_time, last_2nd_online_time, last_offline_time, last_online_time, first_3rd_offline_time, first_3rd_online_time, first_2nd_offline_time, first_2nd_online_time, first_offline_time, first_online_time, last_3rd_ac_to_dc, last_3rd_dc_to_ac, last_2nd_ac_to_dc, last_2nd_dc_to_ac, last_ac_to_dc, last_dc_to_ac, last_3rd_low_battery_event, last_2nd_low_battery_event, last_low_battery_event, last_3rd_high_battery_temperature_time, last_3rd_high_battery_temperature, last_2nd_high_battery_temperature_time, last_2nd_high_battery_temperature, last_high_battery_temperature_time, last_high_battery_temperature, last_3rd_reboot_time, last_3rd_reboot_reason_sub_code, last_2nd_reboot_time, last_2nd_reboot_reason_sub_code, last_reboot_time, last_reboot_reason_sub_code, online_offline_status, online_hours]
        # File info for ftp
        ftp:
          fileName: daily_data
          fileExtension: csv

  # Device monitor and rescue
  savingGateway:
    enable: false
    cronTime: 0 30 15-23,0-1 * * *
    # Creates an array of elements split into groups the length of size
    chunkSize: 50
    scriptInfo:
      returnCode:
        correctGw: 0
        loginFail: 1
        wrongGw: 2
      ipPatt: /^10\.35|36\.*/
      name: SuperUser
      password: 9ABZWZSLF9G61MSWSD7C1Y6EU71GTISU
      silent: false
      templateCommand: cd script; expect saving_gateway.expt %s %s %s %s
    # Nodemailer options
    sendMail:
      options:
        from: postmaster@smartgaiacloud.com
        to: lee_shen@sercomm.com, louis_shih@Sercomm.com, terry_chen@sercomm.com, eric_kao@sercomm.com, jordan_chen@sercomm.com, henry_shiu@sercomm.com, terry_liu@sercomm.com
        subject: Gateway offline & Camera online
        errorRecipient: ytc0316@msn.com
        errorMessage: Gateway offline & Camera online fail
    # Ftp server info for result to send
    putFtp:
      options:
        host: 10.243.170.74
        user: postmaster
        password: sercomm1234
      path: files/unipol-prod/
    contents:
      - key: savingGateways
        # Mail content for sending
        mail:
          fileName: gateway_offline_camera_online.csv
          tableTitle: Gateway offline & Camera online
          tableHeader:  [index, utc_time, kitcode, code, gw_mac, gw_fw_version, gw_address, camera_mac, camera_fw_version, camera_address]
        # File info for ftp
        ftp:
          fileName: gateway_offline_camera_online
          fileExtension: csv
    specialKits: []

  # Relay cameras system_info to temporary DL for batch f/w upgrade
  relaySystemInfo:
    enable: false
    cronTime: 0,30 * * * * *
    # Creates an array of elements split into groups the length of size
    chunkSize: 10
    interval: 30
    # Query string for elasticsearch
    queryStr: message:(CAM_INFO REPEATER_INFO)
    # Wait for Logstash to fill the data, and then shift time point for searching
    shift: forward
    shiftInterval: 30
    param:
      # Report type for console log
      reportType:
          camera: CAM_INFO
          repeater: REPEATER_INFO
      # The array of payload keys that match the regular expression result
      payloadKeys: [{}, {key: MAC, formatTime: false}, {key: DEVICE_NAME, formatTime: false}, {key: IP, formatTime: false}, {key: VIP, formatTime: false}, {key: MODEL, formatTime: false}, {key: FW_VERSION, formatTime: false}, {key: TIMESTAMP, formatTime: true}]
      # The payload template for relayed
      payloadTemplate: <?xml version="1.0" encoding="UTF-8"?><registration><timestamp>{{TIMESTAMP}}</timestamp><mac>{{MAC}}</mac><device_name>{{DEVICE_NAME}}</device_name><ip>{{IP}}</ip><vip>{{VIP}}</vip><model>{{MODEL}}</model><fw_version>{{FW_VERSION}}</fw_version><event_capability><event><by>motion</by></event><event><by>audio</by></event><event><by>httpc</by></event></event_capability></registration>
